### ISSUE TITLE
[Request] Update specific library source only

### ISSUE THREAD

**Issue by zag2me** [robweber/xbmclibraryautoupdate#37]
Is it possible to just update a single source in music rather than the entire library?

This would reduce my Audio Library update time from 25mins to 10 seconds :)

Would be nice for video too.

**Comment by robweber** [comment]
This is possible currently with the Video Library using a "custom path". Just set it to the single source you wanted updated on it's own timer. 

Right now this addon is using Kodi Built In Functions to call the Kodi library scanner. These functions are limited in that you can't specify a music directory. After reading your question though I started to wonder if the JSON-RPC methods offered a way to do this. Turns out they do. I'm going to flag this as an enhancement. It would probably make sense to start using JSON-RPC functions rather than the Built-In functions for this. 

_Links for my own benefit when working on this later_
https://kodi.wiki/view/JSON-RPC_API/v8#AudioLibrary.Scan
https://kodi.wiki/view/JSON-RPC_API/v8#VideoLibrary.Scan

**Comment by zag2me** [comment]
Yep the JSON-RPC was my other option to automate music scanning a little more, but would be nice if an Add-on took care of all that.

Thanks for the detailed reply.

**Comment by robweber** [comment]
Been a while but I haven't forgotten about this. Just pushed some changes to use JSON and then added custom paths for music as well. Will merge the branch after some more testing.
