### ISSUE TITLE
Manual run not working

### ISSUE THREAD

**Issue by robweber** [robweber/xbmclibraryautoupdate#47]
Using the manual run feature prompts to run the update process but then nothing happens.

**Comment by sbraz** [comment]
Apparently it is because the "Only run when idle" option has to be disabled. I saw `NOTICE: service.libraryautoupdate-1.0.2 : Skipping scan, only run when idle` in the logs. After disabling "Only run when idle", it worked.
I've had another issue since I upgraded to Kodi 18: the plugin never ran at all, maybe it was also because of that "idle" thing not working.

**Comment by robweber** [comment]
Thanks for that. I've been playing with this a bit over the past couple weeks on a fresh install and it was always working. Must not have tried it with that combo of settings. I should be able to fix this up now.
