### ISSUE TITLE
It won't work in Kodi 18.6 -- "No module named kodi_six"

### ISSUE THREAD

**Issue by jcollum** [robweber/xbmclibraryautoupdate#68]
```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
   Error Type: <type 'exceptions.ImportError'>
   Error Contents: No module named kodi_six
   Traceback (most recent call last):
     File "/home/media/.kodi/addons/service.libraryautoupdate/default.py", line 1, in <module>
       import resources.lib.utils as utils
     File "/home/media/.kodi/addons/service.libraryautoupdate/resources/lib/utils.py", line 1, in <module>
       from kodi_six import xbmc,xbmcgui,xbmcaddon,xbmcvfs
   ImportError: No module named kodi_six
   -->End of Python script error report<--
```

**Comment by robweber** [comment]
The error is due to the fact that the Kodi Six library is not installed. The library is defined correctly in the [addon.xml](https://github.com/robweber/xbmclibraryautoupdate/blob/leia/addon.xml#L7) file and that addon does exist in the [Kodi addon repository](http://mirrors.kodi.tv/addons/leia/script.module.kodi-six/). Best guess is that Kodi failed to download the addon completely for some reason. You can either download manually or uninstall and reinstall the Library Updater addon to try and get it working.

**Comment by jcollum** [comment]
Is there any for you to check for that library during the install process?
It seems like if you're a requirements or not install then you shouldn't be
continuing with the install, if that is at all possible.

Thanks for the suggestion I will take a look at fixing it.

**Comment by robweber** [comment]
To be honest Kodi is supposed to download and install all dependencies when the addon is installed. I'm not sure in this case why it was missed - seems more like a Kodi problem than anything. If something is specified in the `addon.xml` file as a required module it should pull it in.
